Code for Formative assignment

In [1]:
import pandas as pd

In [22]:
url = "https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations-by-age-group.csv"
covid = pd.read_csv(url)

In [23]:
covid

,location,date,age_group,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred
0,Austria,2021-01-08,18-24,0.12,0.00
1,Austria,2021-01-08,25-49,0.39,0.00
2,Austria,2021-01-08,50-59,0.54,0.00
3,Austria,2021-01-08,60-69,0.32,0.00
4,Austria,2021-01-08,70-79,0.27,0.00
...,...,...,...,...,...
11601,Uruguay,2021-07-09,35-44,81.24,73.55
11602,Uruguay,2021-07-09,45-54,84.00,78.39
11603,Uruguay,2021-07-09,55-64,88.66,84.06
11604,Uruguay,2021-07-09,65-74,89.78,78.87
11605,Uruguay,2021-07-09,75+,88.18,74.81

In [24]:
covid.columns

Index(['location', 'date', 'age_group', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred'],
      dtype='object')

In [25]:
covid.describe

<bound method NDFrame.describe of       location        date age_group  people_vaccinated_per_hundred  \
0      Austria  2021-01-08     18-24                           0.12
1      Austria  2021-01-08     25-49                           0.39
2      Austria  2021-01-08     50-59                           0.54
3      Austria  2021-01-08     60-69                           0.32
4      Austria  2021-01-08     70-79                           0.27
...        ...         ...       ...                            ...
11601  Uruguay  2021-07-09     35-44                          81.24
11602  Uruguay  2021-07-09     45-54                          84.00
11603  Uruguay  2021-07-09     55-64                          88.66
11604  Uruguay  2021-07-09     65-74                          89.78
11605  Uruguay  2021-07-09       75+                          88.18

       people_fully_vaccinated_per_hundred
0                                     0.00
1                                     0.00
2                                     0.00
3                                     0.00
4                                     0.00
...                                    ...
11601                                73.55
11602                                78.39
11603                                84.06
11604                                78.87
11605                                74.81

[11606 rows x 5 columns]>

In [32]:
covid_vac = covid.loc[:,['location','date','age_group','people_fully_vaccinated_per_hundred']]
covid_vac

      location        date age_group  people_fully_vaccinated_per_hundred
0      Austria  2021-01-08     18-24                                 0.00
1      Austria  2021-01-08     25-49                                 0.00
2      Austria  2021-01-08     50-59                                 0.00
3      Austria  2021-01-08     60-69                                 0.00
4      Austria  2021-01-08     70-79                                 0.00
...        ...         ...       ...                                  ...
11601  Uruguay  2021-07-09     35-44                                73.55
11602  Uruguay  2021-07-09     45-54                                78.39
11603  Uruguay  2021-07-09     55-64                                84.06
11604  Uruguay  2021-07-09     65-74                                78.87
11605  Uruguay  2021-07-09       75+                                74.81

[11606 rows x 4 columns]

In [33]:
covid_vac.nunique()

location                                 32
date                                    298
age_group                                30
people_fully_vaccinated_per_hundred    5656
dtype: int64

In [35]:
covid_vac.isnull().sum()

location                                0
date                                    0
age_group                               0
people_fully_vaccinated_per_hundred    15
dtype: int64

In [36]:
covid_vac.dropna(inplace=True)

In [42]:
covid_vac.isnull().sum()

location                               0
date                                   0
age_group                              0
people_fully_vaccinated_per_hundred    0
dtype: int64

In [41]:
covid_vac.value_counts()

location    date        age_group  people_fully_vaccinated_per_hundred
Uruguay     2021-07-09  75+        74.81                                  1
Israel      2021-03-11  90+        88.34                                  1
                        70-79      90.26                                  1
                        60-69      79.53                                  1
                        50-59      73.16                                  1
                                                                         ..
Luxembourg  2021-04-09  50-59      2.96                                   1
                        25-49      2.26                                   1
                        18-24      1.13                                   1
            2021-04-02  80+        36.64                                  1
Austria     2021-01-08  18-24      0.00                                   1
Length: 11591, dtype: int64

In [45]:
covid_vac.head(7)

  location        date age_group  people_fully_vaccinated_per_hundred
0  Austria  2021-01-08     18-24                                  0.0
1  Austria  2021-01-08     25-49                                  0.0
2  Austria  2021-01-08     50-59                                  0.0
3  Austria  2021-01-08     60-69                                  0.0
4  Austria  2021-01-08     70-79                                  0.0
5  Austria  2021-01-08       80+                                  0.0
6  Austria  2021-01-15     18-24                                  0.0

In [46]:
import networkx as nx
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

ModuleNotFoundError: No module named 'cartopy'